apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bases/vault-config/

patches:
  - patch: |-
      - op: replace
        path: /spec/applicationID
        value: 401106 #replace by your Github Org Id here!!!
    target:
      kind: GitHubSecretEngineConfig
  - patch: |-
      - op: replace
        path: /spec/organizationName
        value: "redhat-na-ssa" #replace by your Github Org name here!!!
      - op: replace
        path: /metadata/name
        value: "redhat-na-ssa" #replace by your Github Org name here!!!
    target:
      kind: GitHubSecretEngineRole
  - patch: |-
      - op: replace
        path: /spec/url
        value: "https://quay.io" #replace by your Quay instance URL here!!!
    target:
      kind: QuaySecretEngineConfig
  - patch: |-
      - op: replace
        path: /spec/namespaceName
        value: "redhat-na-ssa" #replace by your Quay Organization/namespace here!!!
      - op: replace
        path: /metadata/name
        value: "redhat_na_ssa" #replace by your Quay Organization/namespace here!!!
    target:
      kind: QuaySecretEngineRole